### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by littlemooon**

### CODE REVIEW

**Review by jorilallo — APPROVED** [review]
Lets merge after SDK and client are combined under `@linear/client`

**Comment by eldh** [comment]
Big boi
image

**Comment by dotansimha** [comment]
I love it, @littlemooon :) Feel free to reach out you need any help with codegen ;) We are also a users of Linear at https://the-guild.dev/ :)

**Comment by littlemooon** [comment]
Thanks @dotansimha 🥰

Couldn't do it without the work of this community 🥳

**Pull request merged**
